apiVersion: v1
kind: Namespace
metadata:
  name: demo-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui-app
  namespace: demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ui-app
  template:
    metadata:
      labels:
        app: demo-ui-app
    spec:
      containers:
      - name: demo-ui
        image: ctcdemo1770171004.azurecr.io/demo-ui:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ui-service
  namespace: demo-ui
spec:
  selector:
    app: demo-ui-app
  ports:
  - port: 80
    targetPort: 8501
  type: ClusterIP